name = "MessagePassingIPA"
uuid = "ae93bb3c-0630-4e85-811e-b7d91ad6ecbd"
authors = ["Kenta Sato <bicycle1885@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
