name = "MessagePassingIPA"
uuid = "ae93bb3c-0630-4e85-811e-b7d91ad6ecbd"
authors = ["Kenta Sato <bicycle1885@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GraphNeuralNetworks = "cffab07f-9bc2-4db1-8861-388f63bf7694"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
GraphNeuralNetworks = "0.6"
julia = "1.9"

[extras]
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Rotations"]
