name = "MessagePassingIPA"
uuid = "ae93bb3c-0630-4e85-811e-b7d91ad6ecbd"
authors = ["Kenta Sato <bicycle1885@gmail.com> and contributors"]
version = "0.0.3"

[deps]
BatchedTransformations = "8ba27c4b-52b5-4b10-bc66-a4fda05aa11b"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GraphNeuralNetworks = "cffab07f-9bc2-4db1-8861-388f63bf7694"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
BatchedTransformations = "0.5"
Flux = "0.13.17, 0.14, 0.15, 0.16"
GraphNeuralNetworks = "0.6, 1"
LinearAlgebra = "1"
julia = "1.10"

[extras]
BatchedTransformations = "8ba27c4b-52b5-4b10-bc66-a4fda05aa11b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BatchedTransformations"]
